# Generated by Django 2.2.2 on 2019-06-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='createed_at',
            new_name='created_at',
        ),
    ]
